# -*- coding: utf-8 -*-
"""Coordenadas_OpenStreetMap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rclj0-wU9Sg4EUwKvRrJ2ZS_KA5L3Fgd
"""

#hasta aqui

import pandas as pd
from geopy.geocoders import Nominatim
from time import sleep

# Leer archivo quitando primeras 4 filas
df = pd.read_excel(
    "BBDD ONSV - SINIESTROS FATALES 2021-2025 (preliminar).xlsx",
    skiprows=4)

# limpiar nombres de columnas
df.columns = df.columns.str.strip()

# crear columna vacía
df["UBICACION"] = ""

# conectar con OpenStreetMap
geolocator = Nominatim(
    user_agent="ubicaciones_csv")


def obtener_direccion(lat, lon):
    try:

        location = geolocator.reverse(
            f"{lat}, {lon}",
            language="es" )

        if not location:
            return None

        addr = location.raw["address"]

        # prioridad: calle / avenida / vía
        candidatos = [
            addr.get("road"),
            addr.get("pedestrian"),
            addr.get("footway"),
            addr.get("path"),
            addr.get("residential"),
            addr.get("service"),]

        for via in candidatos:
            if via:
                return via

        # si no hay vía
        zona = (
            addr.get("suburb")
            or addr.get("city_district")
            or addr.get("town")
            or addr.get("village")
            or addr.get("city"))

        if zona:
            return zona

        # último recurso
        return location.address

    except Exception as e:
        print(f"   Error: {e}")
        return None


total = len(df)

for i, row in df.iterrows():

    lat = row["COORDENADAS LATITUD"]
    lon = row["COORDENADAS  LONGITUD"]

    print(
        f"[{i+1}/{total}] "
        f"Buscando: {lat}, {lon}")

    nombre = obtener_direccion(lat, lon)

    # guardar en fila exacta
    df.at[i, "UBICACION"] = nombre

    print(f"   → {nombre}")

    # guardar parcial cada 50 filas
    if (i + 1) % 50 == 0:

        df.to_excel("coordenadas_con_ubicacion.xlsx",
            index=False )

        print(" Guardado parcial en Excel")

    sleep(1)


# guardar final
df.to_excel(
    "coordenadas_con_ubicacion.xlsx",
    index=False)

print("\nProceso terminado.")
print(
    "Archivo guardado: "
    "coordenadas_con_ubicacion.xlsx")

